### ISSUE TITLE
[bug] 亮色模式下 主页 订阅 热门 排行 收藏 的 fab 配色不正确

### ISSUE THREAD

**Issue by duzhaokun123** [asuka-mio/Ehviewer#39]
**简略描述 / Describe the bug**
亮色模式下 主页 订阅 热门 排行 收藏 的 fab 配色不正确
而且看不清

**如何重现 / To Reproduce**
重现的步骤：
1. 确实应用在亮色模式
2. 打开主页
3. 看右下角 fab

**预期行为 / Expected behavior**
与 搜索 的 fab 配色相同

**截图 / Screenshots**
预期配色
![Screenshot_20220524-193755_EhViewer](https://user-images.githubusercontent.com/39830683/170026472-740e1a01-ca4b-4dfe-9842-ed7db3187788.png)
实际配色
![Screenshot_20220524-193745_EhViewer](https://user-images.githubusercontent.com/39830683/170026544-2deccb5d-0107-4c37-b339-d170b0c11d66.png)

**设备型号与 Android 版本 / Device model and Android version**
 - 设备型号：mix2s
 - Android 版本：12L

**备注 / Additional context**
无

**Comment by asuka-mio** [comment]
知道了，hippo造的轮子在我把颜色全扬了用动态取色时候炸了，等我从质感文件抄一个

> **简略描述 / Describe the bug** 亮色模式下 主页 订阅 热门 排行 收藏 的 fab 配色不正确 而且看不清
> 
> **如何重现 / To Reproduce** 重现的步骤：
> 
>     1. 确实应用在亮色模式
> 
>     2. 打开主页
> 
>     3. 看右下角 fab
> 
> 
> **预期行为 / Expected behavior** 与 搜索 的 fab 配色相同
> 
> **截图 / Screenshots** 预期配色 ![Screenshot_20220524-193755_EhViewer](https://user-images.githubusercontent.com/39830683/170026472-740e1a01-ca4b-4dfe-9842-ed7db3187788.png) 实际配色 ![Screenshot_20220524-193745_EhViewer](https://user-images.githubusercontent.com/39830683/170026544-2deccb5d-0107-4c37-b339-d170b0c11d66.png)
> 
> **设备型号与 Android 版本 / Device model and Android version**
> 
>     * 设备型号：mix2s
> 
>     * Android 版本：12L
> 
> 
> **备注 / Additional context** 无
