### ISSUE TITLE
搜索画廊类型添加中文翻译

### ISSUE THREAD

**Issue by wordly123** [asuka-mio/Ehviewer#66]
### 需求 / Requirement

黑色框中的英文画廊类型翻译为中文 

![E56A804D0C141BD060FBD4035DAB29E9](https://user-images.githubusercontent.com/21117763/175805983-2727d5b7-7744-4ae9-b65a-29fe6bb1db3c.jpg)

### 建议实现 / Suggested implements

建议添加开关来控制是否翻译

### 其他细节 / Addition details

暂无

### EhViewer 版本号 / EhViewer version code

1.7.27.6

### EhViewer CI 版本 / EhViewer CI Version

https://github.com/asuka-mio/Ehviewer/actions/runs/2562775408

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/asuka-mio/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/asuka-mio/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/asuka-mio/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/asuka-mio/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个功能。如果您有多个功能请求，烦请发起多个 Issue / Ensure there is only one feature request in this issue. Please make mutiply issue for mutiply feature request
- [X] 您确保已使用最新 CI 版本测试，并且该功能在最新 CI 版本中并未按照预期实现 / This feature don't implement correctly in latest CI version

**Comment by txyyh** [comment]
1. Category 作为 E 站的长期固定字段，其可类比于 GitHub 的 Repository, Issue, Pull Requests, Fork 等词汇。大部分用户会更加熟悉他们的原形式，强行翻译反而会给大部分稍熟悉 E 站的用户造成困扰。
2. Category 包含的词汇意义简单，并且按目前情况将长期保持不变，因而翻译 Category 所带来的成效也甚微。
3. Category 目前并没有公认的中文翻译，自行翻译 Category 需要斟酌用词，难度也不低，翻译结果也不一定能得到大家的公认。

因此，本项目暂不给 Category 添加中文翻译。

**Comment by wordly123** [comment]
1.所以才要添加开关 默认不开启 想翻译的就打开呗
2.翻译这个确实对使用没啥成效，大部分人不会管这个而是全选所以我觉得翻译主要是想让大伙排除不感兴趣类别的画廊
3.这些英文其实挺好翻译的官方也有详细的解释实在不行可以用我给的
我在这列一下&nbsp;
DOUJINSHI 同人志
MANGA 漫画
ARTIST CG 艺术CG
GAME CG 游戏CG
WESTERN 西方
NON-H 无H
IMAGE SET 图集
COSPLAY 角色扮演
MISC 杂项
ASIAN PORN 亚洲的 真人H图(这个标签好像废弃了)
具体可以参考
https://ehwiki.org/wiki/Gallery_Categories
这个链接上官方对类别进行详细的解释





---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年6月26日(周日) 下午5:37
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [asuka-mio/Ehviewer] 搜索画廊类型添加中文翻译 (Issue #66)




  
Category 作为 E 站的长期固定字段，其可类比于 GitHub 的 Repository, Issue, Pull Requests, Fork 等词汇。大部分用户会更加熟悉他们的原形式，强行翻译反而会给大部分稍熟悉 E 站的用户造成困扰。 

Category 包含的词汇意义简单，并且按目前情况将长期保持不变，因而翻译 Category 所带来的成效也甚微。 

Category 目前并没有公认的中文翻译，自行翻译 Category 需要斟酌用词，难度也不低，翻译结果也不一定能得到大家的公认。 
 
因此，本项目暂不给 Category 添加中文翻译。

**Comment by txyyh** [comment]
@wordly123 
1. 时间成本与收益太低，我们目前还有大把轮子要换，这也并非本项目的核心目的。
2. 成效指：汉化对词汇理解带来的帮助。
3. 相比于翻译本身，我们更注重这种行为是否得到了大家的公认。
   而且并不是意思简单翻译就简单的，不同 Category 翻译后的词汇长度控制等等都是考虑因素。如果意思简单翻译就简单，那影视字幕/轻小说译者也就没必要殚精竭虑地去寻求信达雅了。

总而言之，对 Category 所付出的劳动对比其所带来的收益太为不值，我们当下还有更多更有意义的事情要做。因此，在可预见的未来内，我们将不会考虑实现本功能
