### ISSUE TITLE
搜索画廊类型过滤修改样式

### ISSUE THREAD

**Issue by wordly123** [asuka-mio/Ehviewer#67]
### 需求 / Requirement

点击排除某个类型的画廊时修改样式变为删除线

![14160CDB4FF3B5C2A35510B33BC92845](https://user-images.githubusercontent.com/21117763/175806230-3983cdca-5dc4-459a-a7ff-ac703f6393ab.jpg)

### 建议实现 / Suggested implements

类似这样的删除线，可以让用户更加明白其含义
![EC44EB16E3C9A6491039374F4551659D](https://user-images.githubusercontent.com/21117763/175806322-a5a84b96-5785-474d-acef-a35d872bcaac.jpg)

### 其他细节 / Addition details

暂无

### EhViewer 版本号 / EhViewer version code

1.7.27.6

### EhViewer CI 版本 / EhViewer CI Version

https://github.com/asuka-mio/Ehviewer/actions/runs/2562775408

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/asuka-mio/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/asuka-mio/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/asuka-mio/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/asuka-mio/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个功能。如果您有多个功能请求，烦请发起多个 Issue / Ensure there is only one feature request in this issue. Please make mutiply issue for mutiply feature request
- [X] 您确保已使用最新 CI 版本测试，并且该功能在最新 CI 版本中并未按照预期实现 / This feature don't implement correctly in latest CI version

**Comment by txyyh** [comment]
根据 M3 官方指导，使用删除线的做法并未出现（也没被否定）
还是建议使用icon区分。官方做法：
![image](https://user-images.githubusercontent.com/41893946/175806778-fca1c3d6-9d79-45cd-b4a5-e3620ebf335c.png)
感觉较好

**Comment by wordly123** [comment]
> 根据 M3 官方指导，使用删除线的做法并未出现（也没被否定） 还是建议使用icon区分。官方做法： ![image](https://user-images.githubusercontent.com/41893946/175806778-fca1c3d6-9d79-45cd-b4a5-e3620ebf335c.png) 感觉较好

也可以只要是能明显看出来是过滤了这个标签就行

**Comment by txyyh** [comment]
好，之后我们将实现此功能

> 也可以只要是能明显看出来是过滤了这个标签就行
