### ISSUE TITLE
App 图标未随系统改变

### ISSUE THREAD

**Issue by Longway22** [asuka-mio/Ehviewer#77]
### 复现步骤 / Step to reproduce

开关黑夜模式

### 预期行为 / Expected behaviour

ehviewer 图标随系统变更为黄色/黑色

### 实际行为 / Actual Behaviour

图标一直为黑色

### EhViewer 版本号 / EhViewer version code

1.7.27.6

### EhViewer CI 版本 / EhViewer CI Version

https://github.com/asuka-mio/Ehviewer/actions/runs/2610271599

### Android 系统版本 / Android version

Android 12

### 设备信息 / Device info

Google Pixel 5

### 应用日志 / App logs

N/A

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/asuka-mio/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/asuka-mio/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/asuka-mio/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/asuka-mio/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 CI 版本测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest CI version

**Comment by txyyh** [comment]
由于此功能即将被移除，因此我们将不会考虑对其进行修复

未来我们会设计一个通用图标来替代它们
