### ISSUE TITLE
请问作者是nekoinverter本人吗

### ISSUE THREAD

**Issue by ffik** [asuka-mio/Ehviewer#84]
之前neko有做过白e，后来没做了。想问一下这是复刻更新，还是本人继续更新（邮箱写的是neko的）

**Comment by asuka-mio** [comment]
不是

**Comment by txyyh** [comment]
@ffik [Q&A](https://github.com/asuka-mio/Ehviewer/issues/61)
Issue 不接受**任何**与错误报告与问题反馈无关的话题
Discussion 开在那里不是当摆设的，谢谢
