### ISSUE TITLE
“需要解锁”与MIUI“应用锁”功能冲突

### ISSUE THREAD

**Issue by LzNOHentai** [asuka-mio/Ehviewer#89]
### 复现步骤 / Step to reproduce

虽然QA说不解决特定ROM独有问题，姑且还是回报一下。

复现步骤：
1.打开ehviewer的MIUI应用锁（该功能的作用是在打开应用前要求输入密码或指纹识别）
2.打开ehviewer的“需要解锁”功能。
3.完全关闭ehviewer及清除后台。
4.打开一个e-hentai/exhentai链接，系统自动使用ehviewer打开。

### 预期行为 / Expected behaviour

正常通过“应用锁”、“需要解锁”两次输入密码，进入APP。
neko的原版白ehviewer是正常的，看起来是“需要解锁”后才开始加载主界面。

任意关闭“应用锁”或“需要解锁”其中一个功能，都能正常使用。

### 实际行为 / Actual Behaviour

在actions/runs/2650399893的CI版本上表现为直接闪退。

在release的1.7.28.0版本上表现为卡在一个白屏，右划可以正常调出左侧栏（主页、设置等），左滑会变成灰屏（看起来是卡没了解锁页面使得UI没有完全加载，右侧的搜索收藏栏和顶部搜索栏消失）

### EhViewer 版本号 / EhViewer version code

1.7.28.0

### EhViewer CI 版本 / EhViewer CI Version

https://github.com/asuka-mio/Ehviewer/actions/runs/2650399893

### Android 系统版本 / Android version

Android 11-MIUI 12.5-21.11.3

### 设备信息 / Device info

小米10 Ultra

### 应用日志 / App logs

[log-2022-07-12-02-10-18-641.zip](https://github.com/asuka-mio/Ehviewer/files/9086549/log-2022-07-12-02-10-18-641.zip)

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/asuka-mio/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/asuka-mio/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/asuka-mio/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/asuka-mio/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 CI 版本测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest CI version

**Comment by txyyh** [comment]
> [Q&A](https://github.com/asuka-mio/Ehviewer/issues/61) “目前我们不会针对厂商 ROM 做相应的适配”

另外两个类似功能同时开启，发生冲突也很正常

**Comment by LzNOHentai** [comment]
> > [Q&A](https://github.com/asuka-mio/Ehviewer/issues/61) “目前我们不会针对厂商 ROM 做相应的适配”
> 
> 那我直接关 Issue 了，如有时间能力自行 PR
> 
> 另外两个类似功能同时开启，发生冲突也很正常

明白。
顺带一提，设置里打开网页链接的默认应用是Chrome，打开eh链接自动注册为ehviewer。
在Chrome不挂后台的情况下能够自动调用ehviewer打开eh链接，挂后台的情况会使用Chrome。
这算正常情况吗？印象里原版白ehviewer会弹出选择框。

**Comment by txyyh** [comment]
@LzNOHentai 这些东西你去 discussion 问吧

**Comment by asuka-mio** [comment]
> > > [Q&A](https://github.com/asuka-mio/Ehviewer/issues/61) “目前我们不会针对厂商 ROM 做相应的适配”
> > 
> > 
> > 那我直接关 Issue 了，如有时间能力自行 PR
> > 另外两个类似功能同时开启，发生冲突也很正常
> 
> 明白。 顺带一提，设置里打开网页链接的默认应用是Chrome，打开eh链接自动注册为ehviewer。 在Chrome不挂后台的情况下能够自动调用ehviewer打开eh链接，挂后台的情况会使用Chrome。 这算正常情况吗？印象里原版白ehviewer会弹出选择框。

目前aosp12下只要你勾选了这些域名
![Screenshot_20220713-155957](https://user-images.githubusercontent.com/43900799/178684508-0f6e5bfe-011f-4029-a3fc-489e91d60d9c.png)
那所有的这些域名下的链接都会由ehviewer打开，如果你不勾选的话是浏览器打开，aosp11我没用过多长时间 现在手上也没有aosp11的设备了，不是很清楚11的逻辑也没法测试，并且不出一个月我们就要全面迭代至13,有能力自行pr吧

**Comment by asuka-mio** [comment]
另外 那个不是闪退 解锁的逻辑就是你解锁不成功就直接退出应用 无法调起验证服务也属于解锁不成功 因为已经有一个解锁实例（应用锁）在运行了
